<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrdenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ordenes')->insert([
            // 📌 Órdenes Pendientes
            [
                'estado' => 'pendiente',
                'fecha_inicio' => '2024-02-01',
                'fecha_fin' => null,
                'tarea' => 'Aplicación de fertilizante',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 1,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pendiente',
                'fecha_inicio' => '2024-02-10',
                'fecha_fin' => null,
                'tarea' => 'Riego de campo',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 2,
                'id_tratamiento' => null,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pendiente',
                'fecha_inicio' => '2024-02-15',
                'fecha_fin' => null,
                'tarea' => 'Monitoreo de plagas',
                'jefecampo_id' => 3,
                'aplicador_id1' => 1,
                'parcela_id' => 3,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pendiente',
                'fecha_inicio' => '2024-02-20',
                'fecha_fin' => null,
                'tarea' => 'Aplicación de herbicida',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 4,
                'id_tratamiento' => 2,
                'id_maquina' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 📌 Órdenes En Curso
            [
                'estado' => 'en curso',
                'fecha_inicio' => '2024-01-10',
                'fecha_fin' => null,
                'tarea' => 'Siembra de trigo',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 1,
                'id_tratamiento' => null,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'en curso',
                'fecha_inicio' => '2024-01-12',
                'fecha_fin' => null,
                'tarea' => 'Cosecha de maíz',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 2,
                'id_tratamiento' => null,
                'id_maquina' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'en curso',
                'fecha_inicio' => '2024-01-18',
                'fecha_fin' => null,
                'tarea' => 'Labranza del suelo',
                'jefecampo_id' => 3,
                'aplicador_id1' => 1,
                'parcela_id' => 3,
                'id_tratamiento' => null,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'en curso',
                'fecha_inicio' => '2024-01-22',
                'fecha_fin' => null,
                'tarea' => 'Cosecha de girasol',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 4,
                'id_tratamiento' => 1,
                'id_maquina' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 📌 Órdenes Pausadas
            [
                'estado' => 'pausada',
                'fecha_inicio' => '2024-01-05',
                'fecha_fin' => null,
                'tarea' => 'Control de plagas',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 1,
                'id_tratamiento' => 3,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pausada',
                'fecha_inicio' => '2024-01-08',
                'fecha_fin' => null,
                'tarea' => 'Aplicación de fungicida',
                'jefecampo_id' => 3,
                'aplicador_id1' => 1,
                'parcela_id' => 2,
                'id_tratamiento' => 2,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pausada',
                'fecha_inicio' => '2024-01-15',
                'fecha_fin' => null,
                'tarea' => 'Monitoreo del suelo',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 3,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'pausada',
                'fecha_inicio' => '2024-01-20',
                'fecha_fin' => null,
                'tarea' => 'Podado de árboles',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 4,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 📌 Órdenes Completadas
            [
                'estado' => 'completada',
                'fecha_inicio' => '2024-01-02',
                'fecha_fin' => '2024-01-04',
                'tarea' => 'Siembra de maíz',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 1,
                'id_tratamiento' => null,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'completada',
                'fecha_inicio' => '2023-12-10',
                'fecha_fin' => '2023-12-15',
                'tarea' => 'Riego por aspersión',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 2,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'completada',
                'fecha_inicio' => '2024-01-06',
                'fecha_fin' => '2024-01-07',
                'tarea' => 'Aplicación de fertilizante',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 1,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'completada',
                'fecha_inicio' => '2024-01-10',
                'fecha_fin' => '2024-01-11',
                'tarea' => 'Riego de campo',
                'jefecampo_id' => 2,
                'aplicador_id1' => 3,
                'parcela_id' => 2,
                'id_tratamiento' => null,
                'id_maquina' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'completada',
                'fecha_inicio' => '2024-01-18',
                'fecha_fin' => '2024-01-19',
                'tarea' => 'Monitoreo de plagas',
                'jefecampo_id' => 3,
                'aplicador_id1' => 1,
                'parcela_id' => 3,
                'id_tratamiento' => null,
                'id_maquina' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'estado' => 'completada',
                'fecha_inicio' => '2024-01-22',
                'fecha_fin' => '2024-01-23',
                'tarea' => 'Aplicación de herbicida',
                'jefecampo_id' => 1,
                'aplicador_id1' => 2,
                'parcela_id' => 4,
                'id_tratamiento' => 2,
                'id_maquina' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}


